package com.news.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.news.bean.NewsBean;
import com.news.bean.User;
import com.news.bean.UserJoinNewsBean;
import com.news.bean.UserJoinVideo;
import com.news.bean.Video;

import com.news.greendao.NewsBeanDao;
import com.news.greendao.UserDao;
import com.news.greendao.UserJoinNewsBeanDao;
import com.news.greendao.UserJoinVideoDao;
import com.news.greendao.VideoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsBeanDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig userJoinNewsBeanDaoConfig;
    private final DaoConfig userJoinVideoDaoConfig;
    private final DaoConfig videoDaoConfig;

    private final NewsBeanDao newsBeanDao;
    private final UserDao userDao;
    private final UserJoinNewsBeanDao userJoinNewsBeanDao;
    private final UserJoinVideoDao userJoinVideoDao;
    private final VideoDao videoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsBeanDaoConfig = daoConfigMap.get(NewsBeanDao.class).clone();
        newsBeanDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        userJoinNewsBeanDaoConfig = daoConfigMap.get(UserJoinNewsBeanDao.class).clone();
        userJoinNewsBeanDaoConfig.initIdentityScope(type);

        userJoinVideoDaoConfig = daoConfigMap.get(UserJoinVideoDao.class).clone();
        userJoinVideoDaoConfig.initIdentityScope(type);

        videoDaoConfig = daoConfigMap.get(VideoDao.class).clone();
        videoDaoConfig.initIdentityScope(type);

        newsBeanDao = new NewsBeanDao(newsBeanDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        userJoinNewsBeanDao = new UserJoinNewsBeanDao(userJoinNewsBeanDaoConfig, this);
        userJoinVideoDao = new UserJoinVideoDao(userJoinVideoDaoConfig, this);
        videoDao = new VideoDao(videoDaoConfig, this);

        registerDao(NewsBean.class, newsBeanDao);
        registerDao(User.class, userDao);
        registerDao(UserJoinNewsBean.class, userJoinNewsBeanDao);
        registerDao(UserJoinVideo.class, userJoinVideoDao);
        registerDao(Video.class, videoDao);
    }
    
    public void clear() {
        newsBeanDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        userJoinNewsBeanDaoConfig.clearIdentityScope();
        userJoinVideoDaoConfig.clearIdentityScope();
        videoDaoConfig.clearIdentityScope();
    }

    public NewsBeanDao getNewsBeanDao() {
        return newsBeanDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public UserJoinNewsBeanDao getUserJoinNewsBeanDao() {
        return userJoinNewsBeanDao;
    }

    public UserJoinVideoDao getUserJoinVideoDao() {
        return userJoinVideoDao;
    }

    public VideoDao getVideoDao() {
        return videoDao;
    }

}
